### ISSUE TITLE
Copied ck_zones.sql to database using PHP MyAdmin - can't insert new zones

### ISSUE THREAD

**Issue by karlbonitz** [jonitaikaponi/ckSurf#11] opened 2015-07-13 05:20 UTC
Hello,

Hopefully you can help as this seems more along the lines of a bug / possible issue. I set up a brand new server and imported the entire ck_zones.sql file into PHP MyAdmin by uploading the file (I didn't copy all of the SQL text into the database for import). After import, the zones all work fine inside of the map, however when creating new zones for maps that already exist in the database (example: surf_akai_final), the error log within source mod throws error: 

07/12/2015 - 23:13:24: [ckSurf.smx] [ckSurf] SQL Error (SQL_insertZonesCallback): Duplicate entry 'surf_akai_final-2' for key 'PRIMARY'

It does this for any new type of zone. The only editing option that works when using !zones is to edit an existing zone. The only way to fix this issues it to remove ALL of the zones for that particular map and start over. Is this a database import issue, or a possible bug / glitch within the source code?

Thank you for your time, and EXCELLENT surf mod!

**Comment by jonitaikaponi** [comment] 2015-07-13 08:32
Hey,

The issue is in the zones themselves. surf_akai_final's zone ID's start
from 1 instead of 0, so the plugin can't insert new zones.

I coded a fix for this, but can't test it right now, so I'll release it
later today.

Glad you like the plugin!

- Joni

2015-07-13 8:20 GMT+03:00 karlbonitz <notifications@github.com>:

**Comment by jonitaikaponi** [comment] 2015-07-13 17:20
Fixed in 1.17

**Comment by karlbonitz** [comment] 2015-07-13 19:13
Works like a charm! Thank you very much for the fix and quick reply! :D

**Closed** 2015-07-14 07:35 UTC
